version: "3"

services:
  db-server:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
      - MYSQL_USER=abc
      - MYSQL_PASSWORD=abc
    volumes:
      - ./docker-storage/db:/var/lib/mysql
  redis-server:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker-storage/redis:/data
    command: ["redis-server", "--save 60 1", "--loglevel warning"]
